FROM alpine:3.9
MAINTAINER Jorge Obiols <jorge.obiols@gmail.com>
RUN apk add --no-cache \
    git \
    python3 \
    libreoffice-writer \
    libreoffice-calc \
    py-pip \
    xvfb \
    supervisor \
    openjdk-7-jre-base
